### ISSUE TITLE
RunTime Error

### ISSUE THREAD

**Issue by MrOuke** [misobarisic/Diffusion-UI#5] opened 2022-11-30 21:44 UTC
Yet again, I'm getting an error, this time however, everything runs as it should but when I am about to generate a batch, this pops up:
![image](https://user-images.githubusercontent.com/118744157/204914048-c3e969ed-cb66-4853-924f-b6df99ddbb5e.png)

I can tell I need to switch something from false to true but I can't figure out what and how exactly... I searched for that argument there but couldn't find it in the notebook... -__-"

**Comment by misobarisic** [comment] 2022-11-30 22:53
Having the same error. Investigating...

**Comment by misobarisic** [comment] 2022-11-30 23:05
The issue is related to xformers. Make sure to turn it off for now. This means your iterations/second will be lower.

**Comment by MrOuke** [comment] 2022-11-30 23:08
Alright, thank you for looking into it so hastily. I'll do as you say for now. If you find out more or if you'll manage to fix it for good, then let me know!

**Comment by misobarisic** [comment] 2022-12-01 00:48
Fixed in the latest commit

**Closed** 2022-12-04 09:44 UTC
