### ISSUE TITLE
Cannot add middleware after an application has started

### ISSUE THREAD

**Issue by qa13683954882** [misobarisic/Diffusion-UI#14] opened 2023-02-10 19:07 UTC
This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Traceback (most recent call last):
  File "launch.py", line 361, in <module>
    start()
  File "launch.py", line 356, in start
    webui.webui()
  File "/content/stable-diffusion-webui/webui.py", line 232, in webui
    app.add_middleware(GZipMiddleware, minimum_size=1000)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 135, in add_middleware
    raise RuntimeError("Cannot add middleware after an application has started")
RuntimeError: Cannot add middleware after an application has started
Killing tunnel 127.0.0.1:7860 <> https://76dc6223-199c-46e3.gradio.live/

fastapi to 0.90 and it works fine.

Can you repair this problem?

**Comment by misobarisic** [comment] 2023-02-11 11:30
Cannot reproduce.
Did you change any of the settings or did you use the default?

**Comment by misobarisic** [comment] 2023-02-14 18:38
Fixed in the latest commit

**Closed by misobarisic** 2023-02-14 18:38 UTC
