### ISSUE TITLE
Error: train.py

### ISSUE THREAD

**Issue by wekito** [misobarisic/Diffusion-UI#16] opened 2023-02-13 05:09 UTC
/content/drive/MyDrive/AI/stable-diffusion-webui
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]
Commit hash: 44de47784af1fb12cb1cb17b8ea0a983d4ece977
Installing gfpgan
Installing clip
Installing open_clip
Cloning Stable Diffusion into repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into repositories/taming-transformers...
Cloning K-diffusion into repositories/k-diffusion...
Traceback (most recent call last):
  File "launch.py", line 360, in <module>
    prepare_environment()
  File "launch.py", line 302, in prepare_environment
    git_clone(k_diffusion_repo, repo_dir('k-diffusion'), "K-diffusion", k_diffusion_commit_hash)
  File "launch.py", line 162, in git_clone
    run(f'"{git}" -C "{dir}" checkout {commithash}', None, "Couldn't checkout {name}'s hash: {commithash}")
  File "launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't checkout {name}'s hash: {commithash}.
Command: "git" -C "repositories/k-diffusion" checkout 5b3af030dd83e0297272d861c19477735d0317ec
Error code: 1
stdout: <empty>
stderr: error: Your local changes to the following files would be overwritten by checkout:
	train.py
Please commit your changes or stash them before you switch branches.
Aborting

What can i do for solve this problem?, thanks for your attention

**Comment by bobbynus** [comment] 2023-02-13 10:30
Have same issue, just rename File "train.py" to "train.py1" and then it works for me. File train.py will be recreated automaticly.

**Comment by misobarisic** [comment] 2023-02-13 10:48
What are the settings you are trying to use? I have not encountered this issue unfortunately.

Issue is duplicate of #11

**Closed** 2023-02-14 18:43 UTC
